version: '3.8'

services:
  python-container:
    build: .
    volumes:
      - ./files:/home/files
      - ./outcome:/home/outcome
      - ./script.py:/home/script.py
    environment:
      DISPLAY: ':99'              # Ustawienie zmiennej środowiskowej DISPLAY
    ports:
      - "5901:5901"   # Otwórz port VNC dla ewentualnego podglądu
    entrypoint: >
      sh -c "Xvnc :99 -geometry 1366x768 -depth 24 -nolisten tcp &
             export DISPLAY=:99 && 
             python3 /home/script.py || echo 'Python script failed' &&
             tail -f /dev/null"